version: "3"

x-config-host: &config-host ${HOST:-0.0.0.0}
x-config-port: &config-port ${PORT:-8080}

services:
  nonebot:
    build: .
    ports:
      - *config-port
    env_file:
      - .env.prod
    volumes:
      - /home/ht/botdocker/cache_image:/cache_image
    environment:
      ENVIRONMENT: prod
      HOST: *config-host
      PORT: *config-port
      LANG: zh_CN.UTF-8
      CACHE_DIR: /cache_image

    restart: always